# Generated by Django 3.1.2 on 2020-11-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_usermusicdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdb',
            name='real_author',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='musicdb',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
